BLADE-728 update blade sample for gradle 7
drewbrokke/liferay-blade-samples pull request #1
Opened 2023-09-12 13:49 UTC by simonjhy

2023-09-15 23:02 UTC, drewbrokke requested changes
@simonjhy thanks for sending this. I had a couple of comments, please see my inline comments. Thanks!

2023-09-15 23:02 UTC, drewbrokke commented on liferay-workspace-test-integration-sample/settings.gradle
> +		}
Can we remove some of these dependencies from here now that we are on v8.0.8 or workspace?

2023-09-15 23:02 UTC, drewbrokke commented on liferay-workspace-test-integration-sample/modules/sample/sample-test/build.gradle
> -	testModules group: "com.liferay.portal", name: "com.liferay.portal.test.integration", version: "latest.release"
Is changing the versions from `latest.release` related to updating to Gradle 7? If not we should make this change separately.

2023-09-15 23:02 UTC, drewbrokke commented on liferay-workspace-test-integration-sample/gradle.properties
> +liferay.workspace.product = portal-7.4-ga85
Do we need to decrement this version?

2023-09-15 23:02 UTC, drewbrokke commented on liferay-workspace/wars/simple-theme/src/main/webapp/WEB-INF/liferay-plugin-package.properties
> +name=untitled2333333333333
This doesn't seem right - shouldn't this be something like "simple-theme"?

2023-09-15 23:02 UTC, drewbrokke commented on yarn-workspace/settings.gradle
> +		classpath(group: "com.liferay", name: "com.liferay.gradle.plugins.workspace", version: "8.0.3") {
In some places we are using `8.0.8`, in others `latest.release`, and here it's `8.0.3`. Is there a particular reason for this version here?

2023-09-22 06:29 UTC, simonjhy commented on liferay-workspace-test-integration-sample/settings.gradle
> +		}
OK

2023-09-22 07:33 UTC, closed without merging

2023-09-22 07:51 UTC, simonjhy commented on liferay-workspace-test-integration-sample/modules/sample/sample-test/build.gradle
> -	testModules group: "com.liferay.portal", name: "com.liferay.portal.test.integration", version: "latest.release"
I revert this change

2023-09-22 07:54 UTC, simonjhy commented on yarn-workspace/settings.gradle
> +		classpath(group: "com.liferay", name: "com.liferay.gradle.plugins.workspace", version: "8.0.3") {
will use the same versoin 8.0.8 for workspace plugin

2023-09-22 07:55 UTC, simonjhy commented on liferay-workspace/wars/simple-theme/src/main/webapp/WEB-INF/liferay-plugin-package.properties
> +name=untitled2333333333333
ok

2023-09-22 07:56 UTC, simonjhy commented on liferay-workspace-test-integration-sample/gradle.properties
> +liferay.workspace.product = portal-7.4-ga85
change to use portal-7.4-ga94